# Generated by Django 4.1.2 on 2022-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
