# Generated by Django 4.1.2 on 2022-10-09 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birhtdays', to=settings.AUTH_USER_MODEL),
        ),
    ]
